baseurl = "http://www.bettingonsuccess.com/"
canonifyurls = true
copyright = "MIT License"
disqusShortname = "bettingonsuccess-com"
googleAnalytics = "UA-112532163-1"
image = "home-bg.jpg"
languageCode = "en-us"
paginate = 10
publishDir = "docs"
theme = "startbootstrap-clean-blog"
title = "Betting On Success"
[author]
name = "Mr. BoS"
[[menu.main]]
name = "Archives"
url = "/post/"
weight = -160
[[menu.main]]
name = "About"
url = "/about/"
weight = -180
[[menu.main]]
name = "home"
url = "/"
weight = -200
[params]
author = "Mr. BoS"
dateform = "Mon, Jan 2, 2006"
description = "Often the difference between a successful man and a failure is not one's better abilities or ideas, but the courage that one has to bet on his ideas, to take a calculated risk, and to act. -- Maxwell Maltz"
[[params.social]]
title = "twitter"
url = "https://twitter.com/bettingonsuccess"
[[params.social]]
title = "github"
url = "https://github.com/bettingonsuccess"
