baseurl = "http://www.bettingonsuccess.com/"
languageCode = "en-us"
title = "bettingonsuccess.com"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
copyright = "MIT License"
publishDir = "docs"
disqusShortname = "bettingonsuccess-com"
googleAnalytics = "UA-112532163-1"

[author]
  name = "Mr. BoS"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Taking smart risks to acheive financial independence"
  Author = "Mr. BoS"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/bettingonsuccess"
[[params.social]]
  title = "github"
  url = "https://github.com/bettingonsuccess"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -180
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -160
